// <auto-generated />
using System;
using CleanArchitecture.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanArchitecture.Infra.Data.Migrations
{
    [DbContext(typeof(CleanArchitectureDBContext))]
    [Migration("20220508103337_secondMigration")]
    partial class secondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanArchitecture.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Models.ContractLocation", b =>
                {
                    b.Property<int>("ContactLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnulRent")
                        .HasColumnType("int");

                    b.Property<int>("Annulncrease")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractLocationHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("ContractReference")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateExcuteUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReference")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<int>("DurationRetainedUnderIFRS16")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncreaseFrequency")
                        .HasColumnType("int");

                    b.Property<int>("MonthsNumber")
                        .HasColumnType("int");

                    b.Property<int>("PayementFrequency")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrepaidExpensesPayementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrepaidExpensesPeriodCovered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RenewalOption_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("increaseDate")
                        .HasColumnType("int");

                    b.Property<int>("tenant_id")
                        .HasColumnType("int");

                    b.HasKey("ContactLocationId");

                    b.HasIndex("ContractLocationHistoryId");

                    b.ToTable("ContractLocations");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Models.ContractLocationHistory", b =>
                {
                    b.Property<int>("ContractLocationHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnulRent")
                        .HasColumnType("int");

                    b.Property<int>("Annulncrease")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractReference")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateExcuteUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReference")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<int>("DurationRetainedUnderIFRS16")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncreaseFrequency")
                        .HasColumnType("int");

                    b.Property<int>("MonthsNumber")
                        .HasColumnType("int");

                    b.Property<int>("PayementFrequency")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrepaidExpensesPayementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrepaidExpensesPeriodCovered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RenewalOption_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("increaseDate")
                        .HasColumnType("int");

                    b.Property<int>("tenant_id")
                        .HasColumnType("int");

                    b.HasKey("ContractLocationHistoryId");

                    b.ToTable("ContractLocationHistories");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Models.ContractLocation", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Models.ContractLocationHistory", "ContractLocationHistory")
                        .WithMany("ContractLocations")
                        .HasForeignKey("ContractLocationHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
